name: Deploy Automático

on:
  push:
    branches:
      - main   # toda vez que atualizar a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Deploy
        run: echo "Aqui entra o comando do deploy"
